# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
AWSTemplateFormatVersion: "2010-09-09"

Description: Amazon Transcribe Live Call Analytics - LCA (v0.1)

Parameters:

  InstallDemoAsteriskServer:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
    Description: >
      Set to true to automatically install a demo Asterisk server for testing
      Chime Voice Connector streaming.

  DemoSoftphoneAllowedCidr:
    Type: String
    AllowedPattern: "( *|([0-9]{1,3}.){3}[0-9]{1,3}(/([0-9]|[1-2][0-9]|3[0-2])))"
    Description: >
      Ignored if Install Demo Asterisk Server is false.
      CIDR block allowed by demo Asterisk server for soft phone registration.
      Example: '198.51.100.36/32'

  SiprecAllowedCidrList:
    Type: String
    # yamllint disable rule:line-length
    AllowedPattern: "( *|(([0-9]{1,3}.){3}[0-9]{1,3}(/([0-9]|[1-2][0-9]|3[0-2]))))(, *([0-9]{1,3}.){3}[0-9]{1,3}(/([0-9]|[1-2][0-9]|3[0-2])))*"
    # yamllint enable rule:line-length
    Description: >
      Ignored if Install Demo Asterisk Server is true.
      Comma delimited list of public CIDR blocks allowed by Chime Voice Connector for SIPREC source hosts. Mask of /27 to /32 is allowed.
      Example: '198.51.100.0/27, 203.0.113.128/27'

  S3BucketName:
    Type: String
    Description: >
      (Optional) Existing bucket where call recording files will be stored.
      Leave blank to automatically create new bucket.
    # yamllint disable rule:line-length
    AllowedPattern: '( *|(?=^.{3,63}$)(?!^(\d+\.)+\d+$)(^(([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])\.)*([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])$))'
    # yamllint enable rule:line-length

  AudioFilePrefix:
    Type: String
    Default: lca-audio-recordings/
    Description: The Amazon S3 prefix where the audio files will be saved (must end in "/")

  IsContentRedactionEnabled:
    Type: String
    Default: 'false'
    Description: >-
      Enable content redaction from Amazon Transcribe transcription output
    AllowedValues:
      - 'true'
      - 'false'

  TranscribeContentRedactionType:
    Type: String
    Default: PII
    Description: >-
      Type of content redaction from Amazon Transcribe transcription output
    AllowedValues:
      - PII

  TranscribeLanguageCode:
    Type: String
    Description: >-
      Language code to be used for Amazon Transcribe
    Default: en-US
    AllowedValues:
      - en-US
      # - en-GB
      # - es-US
      # - fr-CA
      # - fr-FR
      # - en-AU
      # - it-IT
      # - de-DE
      # - pt-BR
      # - ja-JP
      # - ko-KR
      # - zh-CN

  TranscribePiiEntityTypes:
    Type: String
    Default: BANK_ACCOUNT_NUMBER,BANK_ROUTING,CREDIT_DEBIT_NUMBER,CREDIT_DEBIT_CVV,CREDIT_DEBIT_EXPIRY,PIN,EMAIL,ADDRESS,NAME,PHONE,SSN
    Description: >-
      Select the PII entity types you want to identify or redact. Remove the values that you don't want to redact from the default. DO NOT ADD CUSTOM VALUES HERE.

  CustomVocabularyName:
    Type: String
    Default: ''
    Description: >-
      The name of the vocabulary to use when processing the transcription job. Leave blank if no custom vocabulary to be used. If yes, the custom
      vocabulary must pre-exist in your account.

  AllowedSignUpEmailDomain:
    Type: String
    Description: >-
      Email domain that is allowed to signup using the web UI
    MinLength: 4

  DemoAsteriskDownloadUrl:
    Type: String
    Default: https://downloads.asterisk.org/pub/telephony/asterisk/asterisk-16-current.tar.gz
    Description: URL for Asterisk source distribution tar file download - see https://www.asterisk.org/

  DemoAsteriskAgentAudioURL:
    Type: String
    Default: https://s3.<REGION_TOKEN>.amazonaws.com/<ARTIFACT_BUCKET_TOKEN>/<ARTIFACT_PREFIX_TOKEN>/lca-chimevc-stack/demo-audio/agent.wav
    Description: URL for audio (agent.wav) file download for demo Asterisk server.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Telephony Ingestion Options
        Parameters:
          - InstallDemoAsteriskServer
          - DemoSoftphoneAllowedCidr
          - SiprecAllowedCidrList
      - Label:
          default: Web UI Authentication
        Parameters:
          - AllowedSignUpEmailDomain
      - Label:
          default: Amazon S3 Configuration
        Parameters:
          - S3BucketName
          - AudioFilePrefix
      - Label:
          default: Amazon Transcribe Configuration
        Parameters:
          - IsContentRedactionEnabled
          - TranscribeLanguageCode
          - TranscribeContentRedactionType
          - TranscribePiiEntityTypes
          - CustomVocabularyName
      - Label:
          default: Download locations
        Parameters:
          - DemoAsteriskDownloadUrl
          - DemoAsteriskAgentAudioURL
    ParameterLabels:
      S3BucketName:
        default: Call Audio Recordings Bucket Name
      AudioFilePrefix:
        default: Audio File Prefix
      AllowedSignUpEmailDomain:
        default: Authorized Account Email Domain
      InstallDemoAsteriskServer:
        default: Install Demo Asterisk Server
      DemoSoftphoneAllowedCidr:
        default: Allowed CIDR Block for Demo Softphone
      SiprecAllowedCidrList:
        default: Allowed CIDR List for Siprec Integration
      IsContentRedactionEnabled:
        default: Enable Content Redaction for Transcripts
      TranscribeLanguageCode:
        default: Language for Transcription
      TranscribeContentRedactionType:
        default: Content Redaction Type for Transcription
      TranscribePiiEntityTypes:
        default: Transcription PII Redaction Entity Types
      CustomVocabularyName:
        default: Transcription Custom Vocabulary Name
      DemoAsteriskDownloadUrl:
        default: Demo Asterisk Server Source Code Download URL
      DemoAsteriskAgentAudioURL:
        default: Demo Asterisk Server Agent WAV File Download URL

Resources:

  AISTACK:
    Type: AWS::CloudFormation::Stack
    Properties:
      # yamllint disable rule:line-length
      TemplateURL: https://s3.<REGION_TOKEN>.amazonaws.com/<ARTIFACT_BUCKET_TOKEN>/<ARTIFACT_PREFIX_TOKEN>/lca-ai-stack/<VERSION_TOKEN>/template.yaml
      # yamllint enable rule:line-length
      Parameters:
        S3BucketName: !Ref S3BucketName
        AudioFilePrefix: !Ref AudioFilePrefix
        AllowedSignUpEmailDomain: !Ref AllowedSignUpEmailDomain
        IsContentRedactionEnabled: !Ref IsContentRedactionEnabled
        TranscribeContentRedactionType: !Ref TranscribeContentRedactionType
        TranscribeLanguageCode: !Ref TranscribeLanguageCode
        TranscribePiiEntityTypes: !Ref TranscribePiiEntityTypes
        CustomVocabularyName: !Ref CustomVocabularyName

  CHIMEVCSTACK:
    Type: AWS::CloudFormation::Stack
    Properties:
      # yamllint disable rule:line-length
      TemplateURL: https://s3.<REGION_TOKEN>.amazonaws.com/<ARTIFACT_BUCKET_TOKEN>/<ARTIFACT_PREFIX_TOKEN>/lca-chimevc-stack/template.yaml
      # yamllint enable rule:line-length
      Parameters:
        InstallDemoAsteriskServer: !Ref InstallDemoAsteriskServer
        DemoSoftphoneAllowedCidr: !Ref DemoSoftphoneAllowedCidr
        SiprecAllowedCidrList: !Ref SiprecAllowedCidrList
        DemoAsteriskDownloadUrl: !Ref DemoAsteriskDownloadUrl
        DemoAsteriskAgentAudioURL: !Ref DemoAsteriskAgentAudioURL

Outputs:

  CloudfrontEndpoint:
    Description: Endpoint for Cloudfront distribution
    Value: !GetAtt AISTACK.Outputs.CloudfrontEndpoint

  RecordingsS3Bucket:
    Description: Bucket contains all the call recordings
    Value: !GetAtt AISTACK.Outputs.S3BucketName

  DemoPBXIPAddress:
    Description: Demo Asterisk Server IP Address
    Value: !GetAtt CHIMEVCSTACK.Outputs.DemoPBXIPAddress

  DemoPBXPhoneNumber:
    Description: Demo Asterisk Server Phone Number
    Value: !GetAtt CHIMEVCSTACK.Outputs.DemoPBXPhoneNumber

  AsteriskInstanceId:
    Description: Demo Asterisk Server EC2 instanceId
    Value: !GetAtt CHIMEVCSTACK.Outputs.AsteriskInstanceId
